#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using Data;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "BookstoreDB")]
	public partial class TestDBContextDataContext : System.Data.Linq.DataContext, IDBContextDataContext
	{

		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

		#region Extensibility Method Definitions
		partial void OnCreated();
		partial void InsertBooks(Books instance);
		partial void UpdateBooks(Books instance);
		partial void DeleteBooks(Books instance);
		partial void InsertSuppliers(Suppliers instance);
		partial void UpdateSuppliers(Suppliers instance);
		partial void DeleteSuppliers(Suppliers instance);
		partial void InsertClients(Clients instance);
		partial void UpdateClients(Clients instance);
		partial void DeleteClients(Clients instance);
		partial void InsertEvents(Events instance);
		partial void UpdateEvents(Events instance);
		partial void DeleteEvents(Events instance);
		#endregion

		public TestDBContextDataContext() :
				base(global::Tests.Properties.Settings.Default.BookstoreDBConnectionString, mappingSource)
		{
			OnCreated();
		}

		public TestDBContextDataContext(string connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public TestDBContextDataContext(System.Data.IDbConnection connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public TestDBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public TestDBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public System.Data.Linq.Table<Books> Books
		{
			get
			{
				return this.GetTable<Books>();
			}
		}

		public System.Data.Linq.Table<Suppliers> Suppliers
		{
			get
			{
				return this.GetTable<Suppliers>();
			}
		}

		public System.Data.Linq.Table<Clients> Clients
		{
			get
			{
				return this.GetTable<Clients>();
			}
		}

		public System.Data.Linq.Table<Events> Events
		{
			get
			{
				return this.GetTable<Events>();
			}
		}
	}

	
	
	
	
	
	
}
#pragma warning restore 1591
